name: 'maven-settings-temporary'
description: 'Create maven settings (~/.m2/settings.xml)'
branding:
  icon: feather
  color: orange
inputs:
  servers:
    description: 'json array of servers to add to settings.xml'
    required: false
  mirrors:
    description: 'json array of mirrors to add to settings.xml'
    required: false
  repositories:
    description: 'json array of repositories to add to settings.xml'
    required: false
  plugin_repositories:
    description: 'json array of plugin repositories to add to settings.xml'
    required: false
  profiles:
    description: 'json array of profiles to add to settings.xml'
    required: false
runs:
  using: 'node12'
  pre: 'scripts/setup.sh'
  main: 'dist/index.js'
